"""Init

Revision ID: 36c015fd8b69
Revises: 
Create Date: 2024-06-28 21:01:06.965269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c015fd8b69'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contacts', 'birth_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint('contacts_email_key', 'contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contacts_email_key', 'contacts', ['email'])
    op.alter_column('contacts', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
